### PR TITLE
fix fifo

### PR DESCRIPTION
**Pull request by timbreitkreutz**
For testing

### CODE REVIEW

**Comment by timbreitkreutz** [comment]
When I tried cleaning up this Repo, @stevedrip was no longer able to bundle install.  So I plan to leave these PRs as is until we upgrade to 3.3.1 in https://github.com/DripEmail/drip/pull/10774

**Comment by timbreitkreutz** [comment]
Stale.

**Comment by tayjohno** [comment]
@timbreitkreutz since this fork appears to have been merged upstream, are we good to point back to the main repo in our gemfile?

**Comment by timbreitkreutz** [comment]
Yeah probably! :)  But I think #4 is the more important one.

**Pull request closed without merging**
